apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: minitoolstream-ingress-pdb
  namespace: minitoolstream
  labels:
    app: minitoolstream-ingress
    component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: minitoolstream-ingress
  unhealthyPodEvictionPolicy: AlwaysAllow
